// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6DkRLBjqOM_ZetiiYjk8TCNkNrTCNjM',
    appId: '1:102504585682:web:68e42aa52f1a6a49ef500b',
    messagingSenderId: '102504585682',
    projectId: 'aplikacja-drony-mycie',
    authDomain: 'aplikacja-drony-mycie.firebaseapp.com',
    storageBucket: 'aplikacja-drony-mycie.firebasestorage.app',
    measurementId: 'G-R1WNH540HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuefyaGCZs-dVn_kUEmzM7HeXC3YFiuY',
    appId: '1:102504585682:android:1b0b0bbaaf9eef76ef500b',
    messagingSenderId: '102504585682',
    projectId: 'aplikacja-drony-mycie',
    storageBucket: 'aplikacja-drony-mycie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBoxSB9W6q8ZOnUJm43WKrYKwYf8ytd9U',
    appId: '1:102504585682:ios:a2540bdfb9907059ef500b',
    messagingSenderId: '102504585682',
    projectId: 'aplikacja-drony-mycie',
    storageBucket: 'aplikacja-drony-mycie.firebasestorage.app',
    iosBundleId: 'com.karol.firmaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBoxSB9W6q8ZOnUJm43WKrYKwYf8ytd9U',
    appId: '1:102504585682:ios:a2540bdfb9907059ef500b',
    messagingSenderId: '102504585682',
    projectId: 'aplikacja-drony-mycie',
    storageBucket: 'aplikacja-drony-mycie.firebasestorage.app',
    iosBundleId: 'com.karol.firmaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd6DkRLBjqOM_ZetiiYjk8TCNkNrTCNjM',
    appId: '1:102504585682:web:fd4ebc23e2d35b85ef500b',
    messagingSenderId: '102504585682',
    projectId: 'aplikacja-drony-mycie',
    authDomain: 'aplikacja-drony-mycie.firebaseapp.com',
    storageBucket: 'aplikacja-drony-mycie.firebasestorage.app',
    measurementId: 'G-5RXLTXEPJR',
  );
}
